### ISSUE TITLE
Makes creation of abstract and doi columns more modular

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#11]
As of now, the doi column is created inside the CreateOutput method as follows:

https://github.com/popbr/abstract_doi_finder/blob/7180fceba3880188879aa395b2a2f7da7fda4e1a/abstract_doi_finder/src/main/java/popbr/AbstractDoiFinder.java#L157-L168

We could
- have a method `AddCol(XSSFWorkbook inputWB, String column)` that creates a column `column` at the (say) right of the `title` column if it's not here already, and shift all the rest,
- call this method twice, for doi and abstract.

**Comment by KingAdam2004** [comment]
I have made an attempt to make this specific method more modular. However, I did not base it off of the title column (or any other column), yet. I plan on working on this now, I just wanted to verify that the method worked. Here is the specific commit where it worked: (https://github.com/popbr/abstract_doi_finder/commit/9618cb816090f67a7f55aee2e6466477911538ad)

**Comment by aubertc** [comment]
I have tested it and it seems to work as intended. Even more modularity could help (cf. https://github.com/popbr/abstract_doi_finder/issues/12 ), but it does the job as of now.
