### ISSUE TITLE
Spaces should be trimmed

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#15]
Typically, on that line:

https://github.com/popbr/abstract_doi_finder/blob/178c528f71e7e433ccb08dfccea0fae875ecfb72/abstract_doi_finder/src/main/java/popbr/AbstractDoiFinder.java#L326

Spaces should be ignored, so that `" title"` and `" title "` or even `"                   Title      "` are all accepted.

**Comment by aubertc** [comment]
https://github.com/popbr/abstract_doi_finder/commit/55505824d439d1a9675376bf3bf001d0aa5128e6 should take care of it. Please, review it @KingAdam2004

**Comment by KingAdam2004** [comment]
This issue looks like it should be resolved with this commit. We could run a test with some examples, but it looks like the value of each cell should be trimmed to accommodate for different variations.
