### ISSUE TITLE
Cells "have to exist" for the shifting to work properly?

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#16]
[input.xlsx](https://github.com/popbr/abstract_doi_finder/files/14750889/input.xlsx)

The attached sheet crashes with

```
An abstract column has been inserted for each sheet with a title column with no abstract column already existing.
[WARNING] 
java.lang.IllegalArgumentException: firstMovedIndex, lastMovedIndex out of order
    at org.apache.poi.ss.formula.FormulaShifter.<init> (FormulaShifter.java:83)
    at org.apache.poi.ss.formula.FormulaShifter.createForColumnShift (FormulaShifter.java:126)
    at org.apache.poi.xssf.usermodel.XSSFSheet.shiftColumns (XSSFSheet.java:3032)
    at popbr.AbstractDoiFinder.ShiftColumns (AbstractDoiFinder.java:349)
    at popbr.AbstractDoiFinder.CreateOutput (AbstractDoiFinder.java:276)
    at popbr.AbstractDoiFinder.main (AbstractDoiFinder.java:88)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:840)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.419 s
[INFO] Finished at: 2024-03-25T20:30:46-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.1:java (default-cli) on project Abstract_Finder: An exception occurred while executing the Java class. firstMovedIndex, lastMovedIndex out of order -> [Help 1]
```

but if a cell is given some random value at, say, column 12, then the sheet is processed correctly. My guess is that the spreadsheet does not "create" that cell unless asked explicitly, and that makes the program crash.

**Comment by aubertc** [comment]
This may be a duplicate / solved by https://github.com/popbr/abstract_doi_finder/issues/13

**Comment by KingAdam2004** [comment]
Based on the input given, I would say this issue might be slightly different than the issue we were dealing with earlier. It seems it cannot shift the cells since there is "no cell" there to shift to the right by 1. However, when there is data there (including after every column, even leaving the ones blank), it is able to shift all of it to the right. 

I believe adding something as simple as:

```java
if (cell == null || cell.getCellType() == CellType.BLANK)
  // code just inserts the a value in the specific place
else
  // our current code to shift the columns
```

may fix the issue. However, I fear this may cause an issue when there are blanks between data.

**Comment by aubertc** [comment]
We should try that approach nevertheless, it will still be better. I agree with you that ideally the approach should be "if it's empty let's use it, otherwise let's shift", that seems good enough.

**Comment by KingAdam2004** [comment]
This issue should be fixed by (https://github.com/popbr/abstract_doi_finder/commit/a9bcb0d9e2631fcc678a18966111295e9c9d0fe9)

I've done a bit of testing with the files provided and the file above and it works, but I know you may have some more extensive testing.
