### ISSUE TITLE
Create DOI row in spreadsheet

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#2]
The "doi" row was previously manually created.  I am trying right now to find a way, in this method:

https://github.com/popbr/abstract_doi_finder/blob/c3435a4f567db752b2d550258bbdc6248ec01eaf/abstract_doi_finder/src/main/java/popbr/AbstractDoiFinder.java#L125-L135

to not only copy the input spreadsheet, but also to insert the doi row in the sheets starting from the second one.

**Comment by aubertc** [comment]
This is now done with this part:

https://github.com/popbr/abstract_doi_finder/blob/5c654607f9822e9839851e4312f5cb0ad979bd40/abstract_doi_finder/src/main/java/popbr/AbstractDoiFinder.java#L140-L156

However, it may be the case that my shifting is introducing further complications. We'll have to check that it does not mess the spreadsheet.

**Comment by KingAdam2004** [comment]
I'm going through and seeing which issues we may be able to close. We should be able to close this one since we fixed the issue where the shifting was directly affecting the input given. Once I figure out how to include the commit, I will close this issue out (after our meeting).

**Comment by aubertc** [comment]
Yes, this was addressed with https://github.com/popbr/abstract_doi_finder/commit/9618cb816090f67a7f55aee2e6466477911538ad.
