### ISSUE TITLE
Checking for file closure

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#4]
I believe I was sloppy with the `out.close();` method, and do not always close properly the files / FileOutputStream / XSSFWorkbook I am manipulating. Please check me.

**Comment by aubertc** [comment]
In the log, I had:

> And will process that file.
> Cleaning up unclosed ZipFile for archive /donnees/travail/git/abstract_doi_finder/abstract_doi_finder/input/Publication_Abstracts_Only_Dataset_9-26-23.xlsx
> Number of publications that did not have an abstract on PubMed: 16

**Comment by aubertc** [comment]
> In the log, I had:
> 
> > And will process that file.
> > Cleaning up unclosed ZipFile for archive /donnees/travail/git/abstract_doi_finder/abstract_doi_finder/input/Publication_Abstracts_Only_Dataset_9-26-23.xlsx
> > Number of publications that did not have an abstract on PubMed: 16

For this particular issue, https://github.com/popbr/abstract_doi_finder/commit/106f00ba7192aacb868a9231e32e2f959a24d6bb fixed it.

**Comment by aubertc** [comment]
This may or may not have been fixed by https://github.com/popbr/abstract_doi_finder/commit/53c8f61c6b3e6bd318b0d7a409ace931cc5de02f 
Please, check me (knowing that [`file`s do not need to be closed](https://stackoverflow.com/q/4752266/)).

**Comment by KingAdam2004** [comment]
I have double-checked that all input, output, and workbook streams are closed. Everything is closed within the program and should not require that the system deals with the cleanup. This has been verified with one of the most recent commits that messed with the close methods.

Commit: (https://github.com/popbr/abstract_doi_finder/commit/7180fceba3880188879aa395b2a2f7da7fda4e1a)
